### ISSUE TITLE
the ai seems to randomly give up after the first pipe?

### ISSUE THREAD

**Issue by 18praveenb** [HarkerGameDevelopmentClub/Flappy-Bird#1]

**Comment by 4gatepylon** [comment]
I haven't played this game alot, but it seems to me that the AI keep going just fine. (the ones you don't take control of)

**Comment by 18PatZ** [comment]
Did you press the jump key on said bot?

**Comment by 18praveenb** [comment]
nope, they all died after score went to 1

**Comment by 18praveenb** [comment]
is this just my comp?

**Comment by 18PatZ** [comment]
Latest version?

**Comment by 18praveenb** [comment]
yes

**Comment by 18PatZ** [comment]
Not doing that for me.

**Comment by 4gatepylon** [comment]
Not for me either, we can talk about this during lunch or something if you want.

**Comment by 18praveenb** [comment]
looks like a screen size issue
changing one of the pipe parameters fixes

**Comment by 4gatepylon** [comment]
Close this if you claim to have fixed it.
